### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by kurianbenoy** [OpenNyAI/JB-Manager#6]
- How to install [Jugalbandi Studio](https://www.jugalbandi.ai/) is missing in the README. Can you please mention how to install and setup this software?
- Do you have a docker image published in docker hub. Any plans to do that?

**Comment by varun-heman** [comment]
Hey Kurian,

We've yet to put up Studio. We're in the process of launching a pilot program with a select few organisations. The idea is to test it rigorously. Studio will be a separate repo from Manager, they are interoperable but decoupled. This architecture allows an org to play the role of "bot deployer/designer" and the client is the "bot manager". The bot manager's data is not visible to the bot deployer. The deployer can only contribute the bot design/flow. 

We'd love to connect with you on Studio and include you in some capacity in our pilot.
